### PR TITLE
intended meeting?

### PR DESCRIPTION
**Pull request by marklemay**

### CODE REVIEW

**Comment by ybertot** [comment]
Did you want the title to be "intended meaning?"

**Comment by ybertot** [comment]
Just doing statistics in the math-comp library itself, we see that idP is used on 1044 lines, and on the same line as iffP on 186 lines.  That's about 1/6 of the time.  If we perform the same test in math-comp/odd-order, then the numbers are 518 uses of idP, for only 8 uses in conjunction with iffP (1.5%).  In math-comp/analysis, it's half the time: 87 uses of idP, for 41 uses in conjunction with iffP.

When I started these tests, I thought "often" was too strong, but starting at 1/6, I think it is adequate.  I am not the initial author of this line, but I approve the change.

**Comment by marklemay** [comment]
I think there are a couple ways this could be fixed, 

but I think the word "seldom" is incorrect and probably not intended?

**Comment by gares** [comment]
Thanks

**Review by gares — APPROVED** [review]

**Pull request merged**
